sonar.organization=scannerapp
sonar.projectKey=Jord018_Matrix-frontend
sonar.projectName=Matrix Frontend (Vue)

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
