sonar.organization=jord018
sonar.projectKey=jord018_matrix-backend
sonar.projectName=Matrix Backend (Laravel)

sonar.sources=app,routes,config,database,bootstrap/app.php
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
