sonar.organization=scannerapp
sonar.projectKey=Jord018_Matrix-backend
sonar.projectName=Matrix Backend (Laravel)

sonar.sources=app,routes,config,database,bootstrap/app.php
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
